# Generated by Django 3.2 on 2023-03-25 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Edumate_app', '0001_initial'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(max_length=40)),
                ('assignment_description', models.CharField(max_length=100)),
                ('max_marks', models.FloatField(default=25)),
                ('peer_grade', models.BooleanField(default=False)),
                ('duedate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Assignments',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='ClassTeachers',
            fields=[
                ('class_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=40)),
                ('teach_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edumate_app.teachers')),
            ],
            options={
                'db_table': 'ClassTeachers',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=1000)),
                ('marks', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_data', models.CharField(max_length=1000)),
                ('event_date', models.DateTimeField(default=datetime.datetime.now)),
                ('class_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.classteachers')),
                ('teach_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edumate_app.teachers')),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100, null=True)),
                ('time_limit', models.PositiveBigIntegerField(default=10)),
                ('quiz_date', models.DateTimeField(default=datetime.datetime.now)),
                ('class_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.classteachers')),
                ('teach_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edumate_app.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('question', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.quiz'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('proj_name', models.CharField(max_length=100)),
                ('proj_desc', models.CharField(max_length=300)),
                ('proj_due', models.DateTimeField(default=datetime.datetime.now)),
                ('prog_check', models.CharField(max_length=500)),
                ('num_studs', models.IntegerField(default=2)),
                ('class_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.classteachers')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Plagarism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_similarity', models.FloatField(default=0)),
                ('assignment_id', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.assignments')),
                ('stud_assignment1', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment1', to='Student.submittedassignments')),
                ('stud_assignment2', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment2', to='Student.submittedassignments')),
            ],
            options={
                'db_table': 'similarity',
            },
        ),
        migrations.CreateModel(
            name='PeerGrade',
            fields=[
                ('peergrade_id', models.AutoField(primary_key=True, serialize=False)),
                ('assign_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.assignments')),
                ('peer_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Student.submittedassignments')),
                ('peer_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Student.submittedassignments')),
                ('stud_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edumate_app.students')),
            ],
            options={
                'db_table': 'PeerGrade',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=1000)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.question')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('mem_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.groups')),
                ('stud_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edumate_app.students')),
            ],
            options={
                'db_table': 'Members',
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='pro_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.project'),
        ),
        migrations.CreateModel(
            name='DocumentUniqueID',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_unique_id', models.CharField(max_length=100)),
                ('valid_until', models.CharField(default='1679740192.0571156', max_length=200)),
                ('url', models.CharField(default='', max_length=1000)),
                ('plagarism_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.plagarism')),
            ],
            options={
                'db_table': 'DocumentUniqueID',
            },
        ),
        migrations.CreateModel(
            name='AttStud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_time', models.CharField(max_length=100)),
                ('img_number', models.IntegerField(default=0)),
                ('att_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.attendance')),
                ('stud_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edumate_app.students')),
            ],
            options={
                'db_table': 'AttStud',
            },
        ),
        migrations.CreateModel(
            name='Attendance_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('att_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.attendance')),
            ],
            options={
                'db_table': 'attendance_images',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.classteachers'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edumate_app.teachers'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='class_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.classteachers'),
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('ann_id', models.AutoField(primary_key=True, serialize=False)),
                ('announce_data', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('class_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.classteachers')),
                ('teach_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edumate_app.teachers')),
            ],
            options={
                'db_table': 'Announcements',
            },
        ),
    ]
