# Generated by Django 4.1.2 on 2022-10-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassTeachers',
        ),
    ]
