# Generated by Django 4.1 on 2022-11-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(max_length=40)),
                ('assignment_description', models.CharField(max_length=100)),
                ('class_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Assignments',
            },
        ),
    ]
