# Generated by Django 4.1 on 2023-03-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_alter_documentuniqueid_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1679902445.5057516', max_length=200),
        ),
    ]
