# Generated by Django 4.1 on 2022-11-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0007_alter_classteachers_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerGrade',
            fields=[
                ('peergrade_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_id', models.IntegerField()),
                ('assign_id', models.IntegerField()),
                ('peer_1', models.IntegerField()),
                ('peer_2', models.IntegerField()),
            ],
            options={
                'db_table': 'PeerGrade',
            },
        ),
    ]
