# Generated by Django 4.1 on 2023-03-31 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0008_alter_documentuniqueid_valid_until_delete_peergrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1680271632.9537678', max_length=200),
        ),
        migrations.CreateModel(
            name='Peergrade',
            fields=[
                ('peergrade_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.assignments')),
                ('class_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.classteachers')),
            ],
            options={
                'db_table': 'Peergrade',
            },
        ),
    ]
