# Generated by Django 4.1.3 on 2022-11-19 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0009_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
