# Generated by Django 4.1 on 2023-03-31 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edumate_app', '0001_initial'),
        ('Teacher', '0009_alter_documentuniqueid_valid_until_peergrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1680272075.5609581', max_length=200),
        ),
        migrations.CreateModel(
            name='PeerAssigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_stud_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Edumate_app.students')),
                ('peergrade_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.peergrade')),
                ('stud_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Edumate_app.students')),
            ],
            options={
                'db_table': 'Peerassigns',
            },
        ),
    ]
