# Generated by Django 4.1 on 2023-03-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0010_alter_documentuniqueid_valid_until_peerassigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerassigns',
            name='feedb',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peerassigns',
            name='marks',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1680272533.292382', max_length=200),
        ),
    ]
