# Generated by Django 4.1 on 2022-12-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0010_announcements_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='peer_grade',
            field=models.BooleanField(default=False),
        ),
    ]
