# Generated by Django 4.1 on 2022-12-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0011_announcements_peer_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='peer_grade',
        ),
        migrations.AddField(
            model_name='assignments',
            name='peer_grade',
            field=models.BooleanField(default=False),
        ),
    ]
