# Generated by Django 4.1 on 2023-03-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0012_peergrade_number_of_peers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1680275851.015417', max_length=200),
        ),
        migrations.AlterField(
            model_name='peerassigns',
            name='marks',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
