# Generated by Django 4.1.4 on 2022-12-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0013_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
