# Generated by Django 4.1 on 2023-04-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0013_alter_documentuniqueid_valid_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peergrade',
            name='opt1',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='peergrade',
            name='opt2',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='peergrade',
            name='opt3',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='peergrade',
            name='questions',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1680347545.2175214', max_length=200),
        ),
    ]
