# Generated by Django 4.1.4 on 2022-12-31 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0014_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_id', models.IntegerField()),
                ('class_code', models.CharField(max_length=10)),
                ('event_data', models.CharField(max_length=1000)),
                ('event_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
    ]
