# Generated by Django 4.1 on 2023-04-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0014_peergrade_opt1_peergrade_opt2_peergrade_opt3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerassigns',
            name='options_selec',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1680348873.0604205', max_length=200),
        ),
    ]
