# Generated by Django 4.1 on 2023-04-01 18:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edumate_app', '0001_initial'),
        ('Teacher', '0015_peerassigns_options_selec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grouppeers',
            fields=[
                ('gro_id', models.AutoField(primary_key=True, serialize=False)),
                ('gpeer_name', models.CharField(max_length=100)),
                ('gpeer_desc', models.CharField(max_length=300)),
                ('gpeer_due', models.DateTimeField(default=datetime.datetime.now)),
                ('num_studs', models.IntegerField(default=2)),
                ('marks', models.FloatField()),
                ('class_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.classteachers')),
            ],
            options={
                'db_table': 'Grouppeers',
            },
        ),
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1680373085.1867845', max_length=200),
        ),
        migrations.CreateModel(
            name='Peermembers',
            fields=[
                ('mem_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgro_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.grouppeers')),
                ('stud_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edumate_app.students')),
            ],
            options={
                'db_table': 'Peermembers',
            },
        ),
        migrations.CreateModel(
            name='PeerGroups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('submit_file', models.FileField(blank=True, default=None, null=True, upload_to='Teacher/static/upload/')),
                ('submit_desc', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('marksbyteacher', models.FloatField()),
                ('gro_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.grouppeers')),
                ('submit_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edumate_app.students')),
            ],
            options={
                'db_table': 'Peergroups',
            },
        ),
    ]
