# Generated by Django 4.1 on 2023-04-01 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0016_grouppeers_alter_documentuniqueid_valid_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppeers',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='peergroups',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1680374647.4917994', max_length=200),
        ),
    ]
