# Generated by Django 4.1.3 on 2023-01-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0016_quiz_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
