# Generated by Django 4.1 on 2023-04-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0017_grouppeers_created_date_peergroups_submit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppeers',
            name='num_peers',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1680375476.9308558', max_length=200),
        ),
    ]
