# Generated by Django 4.1.3 on 2023-01-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0017_remove_question_quiz_delete_options_delete_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100, null=True)),
                ('time_limit', models.PositiveBigIntegerField(default=10)),
                ('teach_id', models.IntegerField()),
                ('class_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=1000)),
                ('marks', models.PositiveIntegerField(default=0, null=True)),
                ('quiz', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Teacher.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=1000)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Teacher.question')),
            ],
        ),
    ]
