# Generated by Django 4.1.4 on 2023-01-15 08:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0018_quiz_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
