# Generated by Django 4.1 on 2023-04-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0018_grouppeers_num_peers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1680375662.1138322', max_length=200),
        ),
        migrations.AlterField(
            model_name='peergroups',
            name='marksbyteacher',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
