# Generated by Django 4.1 on 2023-04-01 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0019_alter_documentuniqueid_valid_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1680375818.4805958', max_length=200),
        ),
        migrations.AlterField(
            model_name='peermembers',
            name='pgro_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.peergroups'),
        ),
    ]
