# Generated by Django 3.2 on 2023-04-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0020_alter_documentuniqueid_valid_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1680438555.4305315', max_length=200),
        ),
    ]
