# Generated by Django 3.2 on 2023-04-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0021_alter_documentuniqueid_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='attstud',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1680439165.691854', max_length=200),
        ),
    ]
