# Generated by Django 4.1 on 2023-01-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0021_attendance_class_id_attendance_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttStud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_id', models.IntegerField()),
                ('stud_id', models.IntegerField()),
                ('att_time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'AttStud',
            },
        ),
    ]
