# Generated by Django 4.1 on 2023-04-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0022_auto_20230402_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1680595094.3710272', max_length=200),
        ),
    ]
