# Generated by Django 3.2 on 2023-01-27 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0022_attstud'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
