# Generated by Django 3.2 on 2023-02-18 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_submittedassignments_marks'),
        ('Teacher', '0023_quiz_quiz_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plagarism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_similarity', models.FloatField(default=0)),
                ('assignment_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Teacher.assignments')),
                ('stud_assignment1', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='assignment1', to='Student.submittedassignments')),
                ('stud_assignment2', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='assignment2', to='Student.submittedassignments')),
            ],
            options={
                'db_table': 'similarity',
            },
        ),
    ]
