# Generated by Django 3.2 on 2023-02-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0024_plagarism'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('att_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.attendance')),
            ],
            options={
                'db_table': 'attendance_images',
            },
        ),
    ]
