# Generated by Django 4.1 on 2023-05-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0024_alter_documentuniqueid_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1683369499.9902172', max_length=200),
        ),
        migrations.CreateModel(
            name='PeergradeGroups',
            fields=[
                ('peergrade_id', models.AutoField(primary_key=True, serialize=False)),
                ('questions', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('opt1', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('opt2', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('opt3', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('assignment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.grouppeers')),
                ('class_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.classteachers')),
            ],
            options={
                'db_table': 'Peergrade_Groups',
            },
        ),
    ]
