# Generated by Django 3.2 on 2023-02-23 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edumate_app', '0004_students_is_change_teachers_is_change'),
        ('Teacher', '0025_attendance_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='attstud',
            name='img_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attstud',
            name='att_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.attendance'),
        ),
        migrations.AlterField(
            model_name='attstud',
            name='stud_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Edumate_app.students'),
        ),
    ]
