# Generated by Django 4.1 on 2023-05-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0025_alter_documentuniqueid_valid_until_peergradegroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1683369745.820871', max_length=200),
        ),
    ]
