# Generated by Django 4.1 on 2023-03-17 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0026_auto_20230223_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='duedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
