# Generated by Django 4.1 on 2023-05-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Edumate_app', '0001_initial'),
        ('Teacher', '0026_alter_documentuniqueid_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1683375868.805385', max_length=200),
        ),
        migrations.CreateModel(
            name='PeerAssignsGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedb', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('marks', models.FloatField(blank=True, default=None, null=True)),
                ('options_selec', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('assigned_stud_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Edumate_app.students')),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.peergroups')),
                ('peergrade_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.peergradegroups')),
                ('stud_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Edumate_app.students')),
            ],
            options={
                'db_table': 'Peerassigns_Groups',
            },
        ),
    ]
