# Generated by Django 4.1 on 2023-05-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0027_alter_documentuniqueid_valid_until_peerassignsgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='peergroups',
            name='feedbackbyteacher',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1683467017.1807795', max_length=200),
        ),
    ]
