# Generated by Django 4.1.3 on 2023-05-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0028_peergroups_feedbackbyteacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attstud',
            name='is_cropped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attstud',
            name='img_number',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1683548950.9626882', max_length=200),
        ),
    ]
