# Generated by Django 4.1 on 2023-05-11 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0029_attstud_is_cropped_alter_attstud_img_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1683797452.8897746', max_length=200),
        ),
        migrations.CreateModel(
            name='ReferenceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='Teacher/static/reference/')),
                ('datet', models.DateTimeField(default=datetime.datetime.now)),
                ('class_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.classteachers')),
            ],
            options={
                'db_table': 'referencematerial',
            },
        ),
    ]
