# Generated by Django 4.1 on 2023-05-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0030_alter_documentuniqueid_valid_until_referencematerial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuniqueid',
            name='valid_until',
            field=models.CharField(default='1683874494.387289', max_length=200),
        ),
    ]
