# Generated by Django 4.1 on 2022-10-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edumate_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
