# Generated by Django 4.1 on 2023-01-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edumate_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachers',
            name='is_change',
            field=models.IntegerField(default=0),
        ),
    ]
