# Generated by Django 4.1 on 2022-10-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=10)),
                ('stud_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ClassStudents',
            },
        ),
    ]
