# Generated by Django 3.2 on 2023-03-25 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ClassStudents',
            },
        ),
        migrations.CreateModel(
            name='PeerStudents',
            fields=[
                ('peerstud_id', models.AutoField(primary_key=True, serialize=False)),
                ('as_1_marks', models.FloatField()),
                ('as_2_marks', models.FloatField()),
            ],
            options={
                'db_table': 'PeerStudents',
            },
        ),
        migrations.CreateModel(
            name='Quiz_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_responses', models.TextField(null=True)),
                ('correct_responses', models.TextField(null=True)),
                ('total_marks', models.PositiveSmallIntegerField(default=0)),
                ('marks_breakup', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedAssignments',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('assign_desc', models.CharField(max_length=100)),
                ('assign_file', models.FileField(upload_to='Student/static/upload/')),
                ('marks', models.FloatField(default=None, null=True)),
                ('sub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'SubAssigns',
            },
        ),
    ]
