# Generated by Django 4.1 on 2022-11-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedAssignments',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('assign_desc', models.CharField(max_length=100)),
                ('assign_file', models.FileField(upload_to='')),
                ('assignment_id', models.IntegerField()),
            ],
            options={
                'db_table': 'SubAssigns',
            },
        ),
    ]
