# Generated by Django 3.2 on 2023-03-25 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0001_initial'),
        ('Edumate_app', '0001_initial'),
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignments',
            name='assignment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.assignments'),
        ),
        migrations.AddField(
            model_name='submittedassignments',
            name='stud_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edumate_app.students'),
        ),
        migrations.AddField(
            model_name='quiz_marks',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.classteachers'),
        ),
        migrations.AddField(
            model_name='quiz_marks',
            name='quiz',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.quiz'),
        ),
        migrations.AddField(
            model_name='quiz_marks',
            name='student',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edumate_app.students'),
        ),
        migrations.AddField(
            model_name='peerstudents',
            name='as_peer_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Edumate_app.students'),
        ),
        migrations.AddField(
            model_name='peerstudents',
            name='as_peer_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Edumate_app.students'),
        ),
        migrations.AddField(
            model_name='peerstudents',
            name='assign_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.assignments'),
        ),
        migrations.AddField(
            model_name='peerstudents',
            name='stud_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edumate_app.students'),
        ),
        migrations.AddField(
            model_name='classstudents',
            name='class_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.classteachers'),
        ),
        migrations.AddField(
            model_name='classstudents',
            name='stud_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Edumate_app.students'),
        ),
    ]
