# Generated by Django 3.2 on 2023-03-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_marks',
            name='remarks',
            field=models.TextField(default='None', null=True),
        ),
    ]
