# Generated by Django 4.1 on 2022-11-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_submittedassignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignments',
            name='stud_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submittedassignments',
            name='assign_file',
            field=models.FileField(upload_to='Student/static/upload/'),
        ),
    ]
