# Generated by Django 4.1 on 2023-03-27 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0006_alter_documentuniqueid_valid_until'),
        ('Student', '0003_quiz_marks_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog', models.CharField(max_length=400)),
                ('group_id', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.groups')),
            ],
            options={
                'db_table': 'Progress',
            },
        ),
    ]
