# Generated by Django 3.1.7 on 2022-11-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_submittedassignments_stud_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classstudents',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
