# Generated by Django 4.1 on 2023-05-12 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_delete_peerstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='time_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
