# Generated by Django 4.1.4 on 2023-01-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_quiz_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_marks',
            name='class_id',
            field=models.CharField(max_length=10),
        ),
    ]
