# Generated by Django 4.1 on 2023-01-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_alter_quiz_marks_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignments',
            name='marks',
            field=models.FloatField(default=None, null=True),
        ),
    ]
